# ===============================
# 		DATA SOURCE
# =============================== 
#spring.datasource.url=jdbc:postgresql://localhost:5342/jpa
spring.datasource.url=jdbc:postgresql://localhost/jpa
spring.datasource.username=postgres
spring.datasource.password=root

# ==========================================
#  we must add this config as well for 
#  schema.sql and data.sql could work
# ==========================================

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Naming strategy
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
