spring.datasource.url= jdbc:mysql://localhost:3306/jpa?useSSL=false
spring.datasource.username= root
spring.datasource.password= root

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto= update

spring.jpa.show-sql= true

#spring.jpa.generate-ddl= true
#spring.jpa.open-in-view= false

# ==========================================
#  we must add this config as well for 
#  schema.sql and data.sql could work
# ==========================================

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ===========================================
# 	dev-tools (Need to add dependency)
# ===========================================
spring.devtools.restart.enabled=true
