# ===============================
# 		DATA SOURCE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/caching?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# When using java version JDK11 use with mysql dialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

