#spring.config.activate.on-profile=h2
#spring.config.activate.on-profile=mysql
#spring.config.activate.on-profile=postgres

spring.profiles.active=h2
#spring.profiles.active=mysql
#spring.profiles.active=postgres

# The 2 lines below give same logging only
# 		1. From JPA logging
# 		2. From hibernate (I preferer Hibernate)
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG

#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#spring.jpa.properties.hibernate.format_sql=true

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=false

#spring.jpa.properties.hibernate.generate_statistics=true
#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy

spring.devtools.restart.enabled=true

# 	Logging level
logging.level.ROOT=info

