server.port=8080
#spring.profiles.active=h2

spring.profiles.active=mysql
#spring.profiles.active=postgres

spring.output.ansi.enabled=always

jwt.signing.key=weferuogp8734thq3ncf3948u9\
				p3cnj4fx0-3m8uf3t[83ucnygh\
				fenhadf8ayh9ep9r8fghbsakfo\
				jinfcoer83ucnyghfenhadf8ay\
				h9ep9r8fghbsakfojinfcoer48\
				u9p3cnj4fx0-3m8uf3t[83ucny\
				ghfenhadf8ayh9ep9r8vfergec

#weferuogp8734thq3ncf3948u9p3cnj4fx0-3m8uf3t[83ucnyghfenhadf8ayh9ep9r8fghbsakfojinfcoer83ucnyghfenhadf8ayh9ep9r8fghbsakfojinfcoer48u9p3cnj4fx0-3m8uf3t[83ucnyghfenhadf8ayh9ep9r8vfergec

# ---- JPA logging ----
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# ---- Hibernate logging ----
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ===========================================
# 	dev-tools (Need to add dependency)
# ===========================================
spring.devtools.restart.enabled=true



