# ===============================
# 		DATA SOURCE
# =============================== 
spring.datasource.url=jdbc:postgresql://localhost/caching
spring.datasource.username=postgres
spring.datasource.password=root

#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true