###############
#  01 
###############

server.port=8080
spring.profiles.active=mysql

jwt.signing.key=weferuogp8734thq3ncf3948u9\
				p3cnj4fx0-3m8uf3t[83ucnygh\
				fenhadf8ayh9ep9r8fghbsakfo\
				jinfcoer83ucnyghfenhadf8ay\
				h9ep9r8fghbsakfojinfcoer48\
				u9p3cnj4fx0-3m8uf3t[83ucny\
				ghfenhadf8ayh9ep9r8vfergec

#logging.level.org.springframework.web=trace
#logging.level.org.springframework.core=trace
#logging.level.org.springframework.security.web=trace
#logging.level.org.springframework.security.web.access=trace
 
#logging.level.org.springframework.security=trace
#logging.level.org.springframework.security.authentication=trace
#logging.level.org.springframework.security.authentication.dao=trace


#logging.level.org.apache.coyote.http11=trace
#logging.level.javax.servlet=trace

# ==========================================
# format the returned error format 
# when exception is thrown back to client
# ==========================================
server.error.path=/
server.error.include-binding-errors=always
server.error.include-exception=true
server.error.include-message=always
server.error.include-stacktrace=never
server.error.whitelabel.enabled=true