# ===============================
# 		DATA SOURCE
# =============================== 
spring.datasource.url=jdbc:mysql://localhost:3306/transaction_management?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root


# ==========================================
#  we must add this config as well for 
#  schema.sql and data.sql could work
# ==========================================

# this is in order to use data.sql for mysql connection 
# by setting the platform as shMysql
# then modifying `data.sql` to `data-shMysql.sql`  
spring.sql.init.platform=shMysql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# When using java version JDK11 use with mysql dialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
