server.port=8080
spring.profiles.active=mysql

# ==========================================
# format the returned error format 
# when exception is thrown back to client
# ==========================================

server.error.include-binding-errors=always
server.error.include-exception=true
server.error.include-message=always
server.error.include-stacktrace=never
server.error.whitelabel.enabled=true