# ===============================
# 		DATA SOURCE
# =============================== 
#spring.datasource.url=jdbc:postgresql://localhost:5342/jpa
spring.datasource.url=jdbc:postgresql://localhost/jpa
spring.datasource.username=postgres
spring.datasource.password=postgres

# ==========================================
#  we must add this config as well for 
#  schema.sql and data.sql could work
# ==========================================

# this is in order to use data.sql for postgresql connection 
# by setting the platform as shPostgres
# then modifying `data.sql` to `data-shPostgres.sql`  
spring.sql.init.platform=shPostgres
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Naming strategy
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
