server.port=8080

jwt.signing.key.secret=mySecret
jwt.get.token.uri=/authenticate
jwt.refresh.token.uri=/refresh
jwt.http.request.header=Authorization
jwt.token.expiration.in.seconds=604800

##########################################
#	JPA properties
##########################################

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

##########################################
#	Init DB with data.sql file properties
##########################################

#this property is to make it possible to initialized the DB from file nmaed data.sql (Which we create)
spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.datasource.platform=mysql
#spring.datasource.initialization-mode=always

##########################################
#	H2 in memory DB properties
##########################################

spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enabling H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#----------------------------------------------------------
#----------------------------------------------------------