# Use SLF4J for logging
appender=com.p6spy.engine.spy.appender.Slf4JLogger
appender.slf4j.loggingCategory=SQL

# Pretty multi-line format
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat