spring.output.ansi.enabled=always

# Set default timezone for Jackson
spring.jackson.time-zone=Asia/Jerusalem

# Optional: choose how dates/timestamps should look
#spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssZ
#spring.jackson.date-format=dd-MM-yyyy'T'HH:mm:ssZ
