###############
#  09
###############

server.port=8080
spring.profiles.active=mysql

# ==========================================
# format the returned error format 
# when exception is thrown back to client
# ==========================================

#server.error.include-binding-errors=always
#server.error.include-exception=true
#server.error.include-message=always
#server.error.include-stacktrace=never
#server.error.whitelabel.enabled=true

# ===============================
# 	 	JPA / HIBERNATE
# ===============================
 
#Spring will create a schema
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true

# This is OSIV , define it as false for better performance
spring.jpa.open-in-view=false

# show SQL logging
spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.properties.hibernate.generate_statistics=true

# When using java version JDK11 use with mysql dialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

# ===========================================
# 	dev-tools (Need to add dependency)
# ===========================================
spring.devtools.restart.enabled=true
