# ===============================
# 		DATA SOURCE
# =============================== 
#spring.datasource.url=jdbc:postgresql://localhost:5342/jpa
spring.datasource.url=jdbc:postgresql://localhost/jpa
spring.datasource.username=postgres
spring.datasource.password=root

# ==========================================
#  we must add this config as well for 
#  schema.sql and data.sql could work
# ==========================================

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
