# ===============================
# 		DATA SOURCE
# =============================== 
spring.datasource.url=jdbc:postgresql://localhost/jwt
spring.datasource.username=postgres
spring.datasource.password=root

###############################
# Spring will create a schema
###############################
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.generate-ddl=true
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.generate_statistics=true
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# ==========================================
#  we must add this config as well for 
#  schema.sql and data.sql could work
# ==========================================


# this is in order to use data.sql for postgresql connection 
# by setting the platform as shPostgres
# then modifying `data.sql` to `data-shPostgres.sql`  
spring.sql.init.platform=PostGreSql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect