INSERT INTO users_tb(id, username, password, email) VALUES(1, 'sshb', '', 's@s.com');
INSERT INTO users_tb(id, username, password, email) VALUES(2, 'karin', '', 'k@a.com');
INSERT INTO users_tb(id, username, password, email) VALUES(3, 'avigail', '', 'av@av.com');
INSERT INTO users_tb(id, username, password, email) VALUES(4, 'ariel', '', 'ar@ar.com');
INSERT INTO users_tb(id, username, password, email) VALUES(5, 'odel', '', 'o@o.com');
INSERT INTO users_tb(id, username, password, email) VALUES(6, 'itamar', '', 'i@i.com');
INSERT INTO users_tb(id, username, password, email) VALUES(7, 'u1', '', 'u1@t.com');
INSERT INTO users_tb(id, username, password, email) VALUES(8, 'u2', '', 'u2@t.com');
INSERT INTO users_tb(id, username, password, email) VALUES(9, 'u3', '', 'u3@t.com');
INSERT INTO users_tb(id, username, password, email) VALUES(10, 'u4', '', 'u4@t.com');
INSERT INTO users_tb(id, username, password, email) VALUES(11, 'u5', '', 'u5@t.com');
INSERT INTO users_tb(id, username, password, email) VALUES(12, 'u6', '', 'u6@t.com');
INSERT INTO users_tb(id, username, password, email) VALUES(13, 'u7', '', 'u7@t.com');

INSERT INTO roles_tb(id,role,user_id) VALUES(1,'SUPERADMIN',1);
INSERT INTO roles_tb(id,role,user_id) VALUES(2,'ADMIN',1);
INSERT INTO roles_tb(id,role,user_id) VALUES(3,'SUPERADMIN',2);
INSERT INTO roles_tb(id,role,user_id) VALUES(4,'ADMIN',2);
INSERT INTO roles_tb(id,role,user_id) VALUES(5,'ADMIN',3);
INSERT INTO roles_tb(id,role,user_id) VALUES(6,'ADMIN',4);
INSERT INTO roles_tb(id,role,user_id) VALUES(7,'ADMIN',5);
INSERT INTO roles_tb(id,role,user_id) VALUES(8,'ADMIN',6);
INSERT INTO roles_tb(id,role,user_id) VALUES(9,'USER',7);
INSERT INTO roles_tb(id,role,user_id) VALUES(10,'USER',8);
INSERT INTO roles_tb(id,role,user_id) VALUES(11,'USER',9);
INSERT INTO roles_tb(id,role,user_id) VALUES(12,'USER',10);
INSERT INTO roles_tb(id,role,user_id) VALUES(13,'USER',11);
INSERT INTO roles_tb(id,role,user_id) VALUES(14,'USER',12);
INSERT INTO roles_tb(id,role,user_id) VALUES(15,'USER',13);
