spring.application.name=delete

spring.datasource.url=jdbc:postgresql://localhost/test
spring.datasource.username=postgres
spring.datasource.password=postgres

# Spring will create a schema
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.output.ansi.enabled=always

# disable OSIV
spring.jpa.open-in-view=false

# ===========================================
# 	dev-tools (Need to add dependency)
# ===========================================
spring.devtools.restart.enabled=true

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show transaction boundaries and behavior
logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.transaction.interceptor=TRACE

# If using @Transactional with proxies
logging.level.org.springframework.aop.framework=TRACE


# Detailed SQL in logs
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Hibernate transaction logging
logging.level.org.hibernate.transaction=TRACE
logging.level.org.hibernate.engine.transaction.internal=TRACE