spring.profiles.active=h2

# for creating data.sql file
spring.jpa.defer-datasource-initialization=true
spring.data.jpa.repositories.bootstrap-mode=default

logging.level.org.springframework.security.web.FilterChainProxy=trace