# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/jpa?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# = JPA / HIBERNATE
# ===============================

#Spring will create a schema
spring.jpa.hibernate.ddl-auto = create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=debug
#spring.jpa.properties.hibernate.generate_statistics=true

# Becuase of following error:
#          WARN 13496 --- [  restartedMain] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. 
#          Therefore, database queries may be performed during view rendering. 
#          Explicitly configure spring.jpa.open-in-view to disable this warning
# BUT,
# 	when using this parameter as set to false, and we are using FetchType.LAZY, it will throw Lazy fetch error
# 	So , 2 options are :
#  1. No to add it at all (this way we still see the warning but it won't affect the lazy loading
#  2. add this : 'spring.jpa.open-in-view=true'  and set it to true, 
#	  this will make  the warining disappear and lazy loading still works as expected 
# Note:
# accordint the following link:
# 	https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
# 	Unfortunately, OSIV (Open Session in View) 
#   is enabled by default in Spring Boot, and OSIV is really a bad idea from a performance and scalability perspective.
#
#	So, make sure that in the application.properties configuration file, you have the following entry:
#		spring.jpa.open-in-view=false
#	This will disable OSIV so that you can handle the LazyInitializationException the right way.
#	Anyway, DO NOT use the following Anti-Patterns as suggested by some of the answers:
#		Open Session in View (OSIV)
# 		hibernate.enable_lazy_load_no_trans
#	Sometimes, a DTO projection is a better choice than fetching entities, and this way, you won't get any LazyInitializationException.
#
# Question: 
#		How to handle the LazyInitializationException the right way?
# Answer:
#		 https://www.youtube.com/watch?v=6p-fuwVxryg&ab_channel=ThorbenJanssen
# Since I'm using JPQL, 
# better use JOIN FETCH is the easiest way in the CustomerRepository 
#
#	@Query("SELECT c FROM Customer c JOIN FETCH c.phoneNumbers")
#	Customer findWithJoinFetchFirstName(String firstname);
# 
#  And in the RestController :
# 
# 	@GetMapping(path = "/Join-Fetch/{firstname}")
#	public Customer getCustomerWithJoinFetchFirstname(@PathVariable("firstname") String firstname) {
#		System.out.println();
#		LOGGER.info("invoke --> getCustomerWithJoinFetchFirstname");
#		return customerDaoImpl.findCustomerWithJoinFetchFirstName(firstname);
#	}

spring.jpa.open-in-view=false

# This will show the Hiberante SQL in the logger in a vertical way 
#	 spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

# ===============================
# dev-tools
# ===============================
spring.devtools.restart.enabled=true

# ==============================================================================
# to Initialize DB by using a file of data.sql need to set the following fetures
# ==============================================================================
#spring.datasource.platform=mysql
#spring.datasource.initialization-mode=always

# =================================================================
#   this is to cotrolor the JSON Format of  Error message to client
# =================================================================
#server.error.path=true
server.error.include-binding-errors=always
server.error.include-exception=true
server.error.include-message=always
server.error.include-stacktrace=never
server.error.whitelabel.enabled=true
