server.port=8080

# ===============================
# 		DATA SOURCE
# =============================== 
#spring.datasource.url=jdbc:mysql://localhost:3306/jwt?useSSL=false&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://localhost:3306/jwt
#spring.datasource.username=root
#spring.datasource.password=root

# ===========================================
# 	H2 In memory DB
# ===========================================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Enabling H2 Console
spring.h2.console.enabled=true

# Custom H2 Console URL from /h2-console to /h2
spring.h2.console.path=/h2-console


# ===============================
# 		Token
# =============================== 
token.secret=wqduwaoch832i823nd023rndw8cwnsjbrls9y96

# ===============================
# 	 	JPA / HIBERNATE / SQL
# ===============================
  
#Spring will create a schema
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
#spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#----------------------------------------------
# This is for SQL Debugging
spring.jpa.properties.hibernate.format_sql=true
# This enables to see in console the queries
# nee to check if it is the same as the line of spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG

# this line will show the values of the fileds of the queries 
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy

# ===========================================
# 	dev-tools (Need to add dependency)
# ===========================================
spring.devtools.restart.enabled=true

# ===========================================
# 	To update DB from data.sql file
# ===========================================
spring.jpa.defer-datasource-initialization=true
#spring.datasource.platform=mysql
#spring.datasource.initialization-mode=always

# ==========================================
# format the returned error format 
# when exception is thrown back to client
# ==========================================

server.error.include-binding-errors=always
server.error.include-exception=true
server.error.include-message=always
server.error.include-stacktrace=never
server.error.whitelabel.enabled=true
