insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10001, 'ZqgxKfuyeRucaJtUhVFcljaskGsAAS', 'shabtay' ,'shalem' ,'shabtay@g.com' ,'$2a$10$MCcH6SYogz4qow3YhD/gX.0i7lpHA17aejs03i5gSu8usPwlAIrb2' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10002, 'UIzQDFBYSFaLMvMhLfvJVRtClspkgS', 'karin' ,'shalem' ,'karin@g.com' ,'$2a$10$0bMS4SHN9wBU5MNGSQWg7.go5UtPS5uQNjZx2TDvADkpnHB2OfvxO' , null, false);
/*
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10003, 'DdBRoxDwmlJCAdioCAZKihKrhvIbpJ', 'avigail' ,'shalem' ,'avigail@g.com' ,'$2a$10$OxVxoLKJ2t84ZLoj6zmdHOJeLUVVFMrR/3xUvHMHPU5r7b9ePbzT.' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10004, 'NbtMyFiOMXKmUgtJjUBaLLAmaGvEqR', 'ariel' ,'shalem' ,'ariel@g.com' ,'$2a$10$apft.DqTZ6Ok5O5uF2Os4u.cr67iCaIOirnuKcK49Dy.RmquFv/Gu' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10005, 'hGwcqShZSnZHpfvuSQorreCbIEHjJM', 'odel' ,'shalem' ,'odel@g.com' ,'$2a$10$Iinwt7t5qk5k1.yzCdc1Ve8/toHN8zeMU0tM88DHjSsR1ser9adjO' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10006, 'DoqGwFmMlbvoSnzhjewCfGuxlnuvVO', 'itamar' ,'shalem' ,'itamar@g.com' ,'$2a$10$bNrJ/kQySYCI9/29u1wYceEbwkLmlaJnrCoXx9OQKBoATM4Laj3De' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10007, 'hXgGELhCFWpgGYIKVcgaVsGxFIQkTv', 'mother' ,'shalem' ,'mother@g.com' ,'$2a$10$9x9llR5rYmyvkusF.3v8Z.B6iwMZ95W.n2QDL7v6oXo11wwbeeHUy' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10008, 'tbYKGEOWMtgTJmTiZIKzrSmAXRNVKo', 'father' ,'shalem' ,'father@g.com' ,'$2a$10$ZkMvzv7nxz0XsVIkq8lRd.NElkCaaIjW0XnJh/1va1BZuTG1mcQCy' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10009, 'mhrFPTHPXwtigjboFOOCPXJsFAYVmO', 'sister' ,'shalem' ,'sister@g.com' ,'$2a$10$u1g1EdoArwM1yFWTPhf57eZ5ViV0rZN298esV7Ae2UNI5t2puD2ya' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10010, 'FmejBFMIsDZgLGBzZgMfsaguYkDbrE', 'brother' ,'shalem' ,'brother@g.com' ,'$2a$10$OHQqkFroaHnxgoMBrWORWuUa/r7Zm5q4yErvjwKLvW9edd4b0Egh.' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10011, 'rxbOoxhYQmubrIrTdDkTxGQCKlzktj', 'boy' ,'shalem' ,'boy@g.com' ,'$2a$10$HY8rf5HYZUSLfTnSkDs2BeagDBbghHKpvE6tabpoUwImmwMLvJVA2' , null, false);
insert into users(id, user_id, first_name ,last_name ,email ,encrypted_password , email_verification_token, email_verification_status) values(10012, 'ZEWjBafknkTFrydNSfahztgFItlokH', 'girl' ,'shalem' ,'girl@g.com' ,'$2a$10$6ImGHmovHZb17a/.QRBXr.3H8EiMQ4b9ilZmq56SRhWAiQp.sizyS' , null, false);
*/

