###############
#  09
###############

server.port=8080
spring.profiles.active=h2
#spring.profiles.active=mysql
#spring.profiles.active=postgres

# ===============================
# 	 	JPA / HIBERNATE
# ===============================
 
#Spring will create a schema
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true

# This is OSIV , define it as false for better performance
spring.jpa.open-in-view=false

# show SQL logging
spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.properties.hibernate.generate_statistics=true
# ===========================================
# 	dev-tools (Need to add dependency)
# ===========================================


# Specific file : Writes to the specified log file for example c:/localdata//app/logging.log
#logging.file.name=log-file.log

# Specific directory --> Writes "spring.log" to the specified directory for example "log-directory"
#logging.file.path=log-directory

# console color enabled
spring.output.ansi.enabled=always

# ===========================================
# 	dev-tools (Need to add dependency)
# ===========================================
spring.devtools.restart.enabled=true
